### ISSUE TITLE
Development Status

### ISSUE THREAD

**Issue by oesah** [oesah/django-angular-dynamic-forms#17]
Hey, so I was thinking about using this repo, but saw that the last update is quite some time ago. Are you planning on maintaining this repo? I am very interested in the solution, was going to build one myself until I stumbled upon yours.

I could contribute, if you don't have the time to maintain it. I think it could be very powerful, if we can manage forms in angular like we do in Django.

**Comment by mesemus** [comment]
Hi,

Unfortunately for this package we have (at my company) moved to vuejs 
so I have no time for maintaining this library (and my angular experience
is fading away).

If you would like to take over the repo, I'd gratefully transfer it to you :)

Thanks,

Mirek

**Comment by oesah** [comment]
Hey Mesemus,

It would be awesome if you could transfer it to me, I am eager to get this up and running.

Thank you!

**Comment by mesemus** [comment]
Sorry for the delay, I've invited you to the repo and initiated the transfer.
Please send me your npmjs username, I'll add you there as well.

Thanks a lot,

Mirek

**Comment by mesemus** [comment]
I've re-triggered the transfer, please let me know if it worked.

Best regards,

Mirek

**Comment by oesah** [comment]
@mesemus Yes, it worked. Thank you for this and also thank you for putting the effort into this project. :)

Anything I need to do npm wise?
